server:
  port: 9191
spring:
  application:
    name: olx-api-gateway
  cloud: 
   gateway:
      routes: 
      - id: login-service
        uri: lb://login-service
        predicates: 
          - Path=/login/user/**
      - id: advertise-service
        uri: lb://advertise-service
        predicates: 
          - Path=/advertise/ad/**
      - id: masterdata-service
        uri: lb://masterdata-service
        predicates: 
          - Path=/master/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka